"""auto_savings and notification updates

Revision ID: 0f191ad76d6f
Revises: e13a9df4d8b2
Create Date: 2026-04-25 18:38:53.196356

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f191ad76d6f"
down_revision: str | Sequence[str] | None = "e13a9df4d8b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first
    op.execute("DROP INDEX IF EXISTS ix_payment_history_execution_date")
    op.execute("DROP INDEX IF EXISTS ix_payment_history_id")
    op.execute("DROP INDEX IF EXISTS ix_payment_history_status")
    op.execute("DROP INDEX IF EXISTS ix_payment_history_user_id")
    op.drop_table("payment_history")

    op.drop_index(
        op.f("ix_recurring_payment_rules_id"), table_name="recurring_payment_rules",
    )
    op.drop_index(
        op.f("ix_recurring_payment_rules_next_run_date"),
        table_name="recurring_payment_rules",
    )
    op.drop_index(
        op.f("ix_recurring_payment_rules_status"), table_name="recurring_payment_rules",
    )
    op.drop_index(
        op.f("ix_recurring_payment_rules_user_id"), table_name="recurring_payment_rules",
    )
    op.drop_table("recurring_payment_rules")

    op.drop_index(op.f("ix_beneficiaries_id"), table_name="beneficiaries")
    op.drop_index(op.f("ix_beneficiaries_user_id"), table_name="beneficiaries")
    op.drop_table("beneficiaries")

    op.drop_index(op.f("ix_payment_settings_id"), table_name="payment_settings")
    op.drop_index(op.f("ix_payment_settings_user_id"), table_name="payment_settings")
    op.drop_table("payment_settings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recurring_payment_rules",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("beneficiary_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("frequency", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("day_of_month", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("day_of_week", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("next_run_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "requires_approval", sa.BOOLEAN(), autoincrement=False, nullable=True,
        ),
        sa.Column("total_executions", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "last_executed_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_execution_status", sa.VARCHAR(), autoincrement=False, nullable=True,
        ),
        sa.Column(
            "last_failure_reason", sa.VARCHAR(), autoincrement=False, nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_id"],
            ["beneficiaries.id"],
            name=op.f("recurring_payment_rules_beneficiary_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("recurring_payment_rules_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("recurring_payment_rules_pkey")),
    )
    op.create_index(
        op.f("ix_recurring_payment_rules_user_id"),
        "recurring_payment_rules",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_payment_rules_status"),
        "recurring_payment_rules",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_payment_rules_next_run_date"),
        "recurring_payment_rules",
        ["next_run_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_payment_rules_id"),
        "recurring_payment_rules",
        ["id"],
        unique=False,
    )
    op.create_table(
        "beneficiaries",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("nickname", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("identifier_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "identifier_value", sa.VARCHAR(), autoincrement=False, nullable=False,
        ),
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_trusted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "verification_method", sa.VARCHAR(), autoincrement=False, nullable=True,
        ),
        sa.Column(
            "verified_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "last_used_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.Column("payment_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "linked_carebank_user_id", sa.VARCHAR(), autoincrement=False, nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["linked_carebank_user_id"],
            ["users.user_id"],
            name=op.f("beneficiaries_linked_carebank_user_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("beneficiaries_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("beneficiaries_pkey")),
    )
    op.create_index(
        op.f("ix_beneficiaries_user_id"), "beneficiaries", ["user_id"], unique=False,
    )
    op.create_index(op.f("ix_beneficiaries_id"), "beneficiaries", ["id"], unique=False)
    op.create_table(
        "payment_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("beneficiary_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("payment_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("payment_method", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "recurring_rule_id", sa.INTEGER(), autoincrement=False, nullable=True,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "execution_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "mockbank_transaction_id", sa.VARCHAR(), autoincrement=False, nullable=True,
        ),
        sa.Column("error_reason", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("idempotency_key", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_id"],
            ["beneficiaries.id"],
            name=op.f("payment_history_beneficiary_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["recurring_rule_id"],
            ["recurring_payment_rules.id"],
            name=op.f("payment_history_recurring_rule_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("payment_history_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("payment_history_pkey")),
        sa.UniqueConstraint(
            "idempotency_key",
            name=op.f("payment_history_idempotency_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_payment_history_user_id"), "payment_history", ["user_id"], unique=False,
    )
    op.create_index(
        op.f("ix_payment_history_status"), "payment_history", ["status"], unique=False,
    )
    op.create_index(
        op.f("ix_payment_history_id"), "payment_history", ["id"], unique=False,
    )
    op.create_index(
        op.f("ix_payment_history_execution_date"),
        "payment_history",
        ["execution_date"],
        unique=False,
    )
    op.create_table(
        "payment_settings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("mpin_hash", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "mpin_threshold",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "auto_approve_trusted", sa.BOOLEAN(), autoincrement=False, nullable=True,
        ),
        sa.Column(
            "daily_limit",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "daily_limit_used_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "daily_limit_used",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "recurring_payment_max",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "max_active_recurring_rules",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("payment_settings_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("payment_settings_pkey")),
    )
    op.create_index(
        op.f("ix_payment_settings_user_id"),
        "payment_settings",
        ["user_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_payment_settings_id"), "payment_settings", ["id"], unique=False,
    )
    # ### end Alembic commands ###
