"""baseline

Revision ID: ba1fd9312fe9
Revises:
Create Date: 2026-03-20 02:37:13.485328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba1fd9312fe9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("account_type", sa.String(), nullable=False),
        sa.Column("mask", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("institution", sa.String(), nullable=True),
        sa.Column("current_balance", sa.Float(), nullable=True),
        sa.Column("available_balance", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("last_statement_date", sa.String(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_index(
        op.f("ix_accounts_account_id"), "accounts", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_accounts_provider_id"), "accounts", ["provider_id"], unique=False
    )
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_table(
        "action_executions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("approval_request_id", sa.Integer(), nullable=True),
        sa.Column("action_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("request_hash", sa.String(), nullable=True),
        sa.Column("request_payload_json", sa.JSON(), nullable=False),
        sa.Column("result_payload_json", sa.JSON(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_action_executions_action_type"),
        "action_executions",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_executions_approval_request_id"),
        "action_executions",
        ["approval_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_executions_id"), "action_executions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_action_executions_idempotency_key"),
        "action_executions",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_executions_request_hash"),
        "action_executions",
        ["request_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_executions_status"),
        "action_executions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_executions_user_id"),
        "action_executions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "action_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("action_type", sa.String(), nullable=False),
        sa.Column("action_payload_json", sa.JSON(), nullable=False),
        sa.Column("policy_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("request_hash", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("linked_execution_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_action_requests_action_type"),
        "action_requests",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_requests_id"), "action_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_action_requests_idempotency_key"),
        "action_requests",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_requests_linked_execution_id"),
        "action_requests",
        ["linked_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_requests_request_hash"),
        "action_requests",
        ["request_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_requests_status"), "action_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_action_requests_user_id"), "action_requests", ["user_id"], unique=False
    )
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("state_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_sessions_id"), "agent_sessions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_sessions_user_id"), "agent_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("intent", sa.String(), nullable=False),
        sa.Column("agent_used", sa.String(), nullable=False),
        sa.Column("agent_response", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_session_id"), "audit_logs", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("current_balance", sa.Float(), nullable=False),
        sa.Column("available_balance", sa.Float(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_balances_id"), "balances", ["id"], unique=False)
    op.create_index(op.f("ix_balances_user_id"), "balances", ["user_id"], unique=True)
    op.create_table(
        "checklist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("recurring_rule_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checklist_items_due_date"),
        "checklist_items",
        ["due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checklist_items_id"), "checklist_items", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_checklist_items_recurring_rule_id"),
        "checklist_items",
        ["recurring_rule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checklist_items_user_id"), "checklist_items", ["user_id"], unique=False
    )
    op.create_table(
        "financial_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("goal_type", sa.String(), nullable=False),
        sa.Column("target_amount", sa.Float(), nullable=True),
        sa.Column("monthly_budget", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_plans_id"), "financial_plans", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_financial_plans_user_id"), "financial_plans", ["user_id"], unique=False
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("request_hash", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "scope", "idempotency_key", name="uq_idempotency_scope_key"
        ),
    )
    op.create_index(
        op.f("ix_idempotency_records_id"), "idempotency_records", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_idempotency_records_idempotency_key"),
        "idempotency_records",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idempotency_records_scope"),
        "idempotency_records",
        ["scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idempotency_records_status"),
        "idempotency_records",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idempotency_records_user_id"),
        "idempotency_records",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("dedupe_key", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedupe_key", name="uq_notification_dedupe"),
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(
        op.f("ix_notifications_kind"), "notifications", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("min_balance_required", sa.Float(), nullable=True),
        sa.Column("interest_rate", sa.Float(), nullable=True),
        sa.Column("eligibility_rules", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(
        op.f("ix_products_provider_id"), "products", ["provider_id"], unique=False
    )
    op.create_index(op.f("ix_products_type"), "products", ["type"], unique=False)
    op.create_table(
        "providers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("channels", sa.JSON(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("support_contact", sa.String(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_providers_id"), "providers", ["id"], unique=False)
    op.create_table(
        "recurring_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("day_of_month", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("next_run_date", sa.Date(), nullable=False),
        sa.Column("autopay_enabled", sa.Boolean(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("trusted_recurring", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("reminder_days_before", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recurring_rules_id"), "recurring_rules", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_recurring_rules_next_run_date"),
        "recurring_rules",
        ["next_run_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_rules_plan_id"), "recurring_rules", ["plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_recurring_rules_user_id"), "recurring_rules", ["user_id"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("merchant", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_category"), "transactions", ["category"], unique=False
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_merchant"), "transactions", ["merchant"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("monthly_salary", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("min_safe_balance", sa.Float(), nullable=False),
        sa.Column("savings_goal_pct", sa.Float(), nullable=False),
        sa.Column("risk_tolerance", sa.String(), nullable=False),
        sa.Column("persistent_expenses_json", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_profiles_id"), "user_profiles", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_profiles_user_id"), "user_profiles", ["user_id"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.drop_index(op.f("ix_user_profiles_id"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_merchant"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_recurring_rules_user_id"), table_name="recurring_rules")
    op.drop_index(op.f("ix_recurring_rules_plan_id"), table_name="recurring_rules")
    op.drop_index(
        op.f("ix_recurring_rules_next_run_date"), table_name="recurring_rules"
    )
    op.drop_index(op.f("ix_recurring_rules_id"), table_name="recurring_rules")
    op.drop_table("recurring_rules")
    op.drop_index(op.f("ix_providers_id"), table_name="providers")
    op.drop_table("providers")
    op.drop_index(op.f("ix_products_type"), table_name="products")
    op.drop_index(op.f("ix_products_provider_id"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_kind"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_idempotency_records_user_id"), table_name="idempotency_records"
    )
    op.drop_index(
        op.f("ix_idempotency_records_status"), table_name="idempotency_records"
    )
    op.drop_index(
        op.f("ix_idempotency_records_scope"), table_name="idempotency_records"
    )
    op.drop_index(
        op.f("ix_idempotency_records_idempotency_key"), table_name="idempotency_records"
    )
    op.drop_index(op.f("ix_idempotency_records_id"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_financial_plans_user_id"), table_name="financial_plans")
    op.drop_index(op.f("ix_financial_plans_id"), table_name="financial_plans")
    op.drop_table("financial_plans")
    op.drop_index(op.f("ix_checklist_items_user_id"), table_name="checklist_items")
    op.drop_index(
        op.f("ix_checklist_items_recurring_rule_id"), table_name="checklist_items"
    )
    op.drop_index(op.f("ix_checklist_items_id"), table_name="checklist_items")
    op.drop_index(op.f("ix_checklist_items_due_date"), table_name="checklist_items")
    op.drop_table("checklist_items")
    op.drop_index(op.f("ix_balances_user_id"), table_name="balances")
    op.drop_index(op.f("ix_balances_id"), table_name="balances")
    op.drop_table("balances")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_session_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_agent_sessions_user_id"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_id"), table_name="agent_sessions")
    op.drop_table("agent_sessions")
    op.drop_index(op.f("ix_action_requests_user_id"), table_name="action_requests")
    op.drop_index(op.f("ix_action_requests_status"), table_name="action_requests")
    op.drop_index(op.f("ix_action_requests_request_hash"), table_name="action_requests")
    op.drop_index(
        op.f("ix_action_requests_linked_execution_id"), table_name="action_requests"
    )
    op.drop_index(
        op.f("ix_action_requests_idempotency_key"), table_name="action_requests"
    )
    op.drop_index(op.f("ix_action_requests_id"), table_name="action_requests")
    op.drop_index(op.f("ix_action_requests_action_type"), table_name="action_requests")
    op.drop_table("action_requests")
    op.drop_index(op.f("ix_action_executions_user_id"), table_name="action_executions")
    op.drop_index(op.f("ix_action_executions_status"), table_name="action_executions")
    op.drop_index(
        op.f("ix_action_executions_request_hash"), table_name="action_executions"
    )
    op.drop_index(
        op.f("ix_action_executions_idempotency_key"), table_name="action_executions"
    )
    op.drop_index(op.f("ix_action_executions_id"), table_name="action_executions")
    op.drop_index(
        op.f("ix_action_executions_approval_request_id"), table_name="action_executions"
    )
    op.drop_index(
        op.f("ix_action_executions_action_type"), table_name="action_executions"
    )
    op.drop_table("action_executions")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_provider_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_account_id"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
